# Generated by Django 5.2.5 on 2025-09-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reference',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('mpesa', 'M-Pesa')], default='card', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.policy'),
        ),
    ]
